### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by mohseniaref** [jimmytseng79/GMT5_tutorials#1]
Hi,

I wonder if the linux version of your code is avalable?

Best Regards,
Mohammad
mohseni.aref@gmail.com

**Comment by jimmytseng79** [comment]
I think some part of code can't work in the Linux version. Maybe you can tell me which section you interest, I translate it into Linux version.

**Comment by mohseniaref** [comment]
Hi,
Thanks so much for your quick answer.I really appreciate the page and scripts.I use google translator to understand but it seems it works.Translating from DOS to bash seems confusing.for me,this page is priority https://jimmytseng79.github.io/GMT5_tutorials/seismicity_meca.html
I wonder if I have your email

best regards,
Mohammad

**Comment by jimmytseng79** [comment]
My email is jimmytseng79@gmail.com. 
I'm sorry about language and operating system, because this course was made for our school (National Cheng Kung Univ.) master student last year. I try to translate the codes into Linux version.

**Comment by mohseniaref** [comment]
Many many thanks.It is one of the best online course about GMT5 that I have ever seen.Congratulation!

**Comment by jimmytseng79** [comment]
I already translate chapter 9 codes into .csh file. The codes can work when they were tested by running on MAC OS 10.10.5. Kindly be reminded to install gnu-sed by "brew install gnu-sed" if you are working on MAC.
